apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wp
  namespace: {{ .Release.Namespace }}
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  {{- if .Values.wordpress.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}